export enum IconEnum {
  Linkedin = 'linkedin',
  Github = 'github',
  Whatsapp = 'whatsapp',
  Instagram = 'instagram',
  Javascript = 'javascript',
  Typescript = 'typescript',
  Html = 'html',
  Css = 'css',
  Sass = 'sass',
  Nextjs = 'nextjs',
  Tailwind = 'tailwind',
  Reactjs = 'reactjs',
  Storybook = 'storybook',
  Webpack = 'webpack',
  Gulp = 'gulp',
  Npm = 'npm',
  Pnpm = 'pnpm',
  Eslint = 'eslint',
  Prettier = 'prettier',
  Git = 'git',
}
